#!/bin/sh
# Regenerates /etc/dynamic-pac-proxy/config.yaml from the UCI config at
# /etc/config/dynamic-pac-proxy. Run by the init script before starting the
# daemon, and by LuCI after saving changes (see luci/controller). The
# daemon itself hot-reloads config.yaml on its own (polls its mtime every
# few seconds), so regenerating it is normally enough — no restart needed
# except when listen_addr changes.

. /lib/functions.sh

OUT="/etc/dynamic-pac-proxy/config.yaml"
TMP="${OUT}.tmp.$$"
HOSTS_TMP="${OUT}.hosts.tmp.$$"

cleanup() { rm -f "$TMP" "$HOSTS_TMP"; }
trap cleanup EXIT

config_load dynamic-pac-proxy

listen_addr=":8080"
advertise_host=""
refresh_interval="15s"
mdns_timeout="2s"
dial_timeout="1s"
failure_cooldown="5s"

load_main() {
	config_get listen_addr "$1" listen_addr ":8080"
	config_get advertise_host "$1" advertise_host ""
	config_get refresh_interval "$1" refresh_interval "15s"
	config_get mdns_timeout "$1" mdns_timeout "2s"
	config_get dial_timeout "$1" dial_timeout "1s"
	config_get failure_cooldown "$1" failure_cooldown "5s"
}
config_foreach load_main main

: > "$HOSTS_TMP"
host_count=0

emit_host() {
	local section="$1"
	local name host_name host_port server_port ri mt dt fc

	config_get name "$section" name ""
	config_get host_name "$section" host_name ""
	config_get host_port "$section" host_port ""
	config_get server_port "$section" server_port ""
	config_get ri "$section" refresh_interval ""
	config_get mt "$section" mdns_timeout ""
	config_get dt "$section" dial_timeout ""
	config_get fc "$section" failure_cooldown ""

	if [ -z "$name" ] || [ -z "$host_name" ] || [ -z "$host_port" ] || [ -z "$server_port" ]; then
		logger -t dynamic-pac-proxy "skipping incomplete host section '$section' (name/host_name/host_port/server_port all required)"
		return
	fi

	{
		echo "  - name: \"$name\""
		echo "    host_name: \"$host_name\""
		echo "    host_port: $host_port"
		echo "    server_port: $server_port"
		[ -n "$ri" ] && echo "    refresh_interval: $ri"
		[ -n "$mt" ] && echo "    mdns_timeout: $mt"
		[ -n "$dt" ] && echo "    dial_timeout: $dt"
		[ -n "$fc" ] && echo "    failure_cooldown: $fc"
	} >> "$HOSTS_TMP"
	host_count=$((host_count + 1))
}
config_foreach emit_host host

{
	echo "# Generated by uci2yaml.sh from /etc/config/dynamic-pac-proxy."
	echo "# Do not edit by hand — changes here are overwritten. Edit via LuCI"
	echo "# (Services > Dynamic PAC Proxy) or \`uci set dynamic-pac-proxy...\` instead."
	echo "listen_addr: \"$listen_addr\""
	if [ -n "$advertise_host" ]; then
		echo "advertise_host: \"$advertise_host\""
	fi
	echo "refresh_interval: $refresh_interval"
	echo "mdns_timeout: $mdns_timeout"
	echo "dial_timeout: $dial_timeout"
	echo "failure_cooldown: $failure_cooldown"
	if [ "$host_count" -eq 0 ]; then
		echo "hosts: []"
	else
		echo "hosts:"
		cat "$HOSTS_TMP"
	fi
} > "$TMP"

mkdir -p "$(dirname "$OUT")"
mv "$TMP" "$OUT"
