#!/bin/sh /etc/rc.common
# OpenWRT procd init script.

USE_PROCD=1
START=99
STOP=10

PROG=/opt/dynamic-pac-proxy/dynamic-pac-proxy
CONF=/opt/dynamic-pac-proxy/config.yaml

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" --config "$CONF"
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
